version: '3.8'

services:
  real-estate-fe:
    build:
      context: .
      dockerfile: Dockerfile
    image: real-estate-fe:latest
    restart: unless-stopped
    ports:
      - 4420:3000
    environment:
      - NODE_ENV=production
      # - NEXTAUTH_URL=http://localhost:4420
      # - NEXTAUTH_SECRET=0g1s1i9EorqlbQJTVhMelnmhrhp7prcr
    networks:
      - default
    # volumes:
    #   - /app/apps/customerweb/.next/cache

networks:
  default:
