import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import ClientProviders from '@/app/client-providers';
import './globals.css';

const geist = Geist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProviders>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClientProviders>
  );
}
