import type { Metadata } from 'next';
import ClientProviders from '@/app/client-providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientProviders>
      <html lang="en" className="real-estate">
        <body>{children}</body>
      </html>
    </ClientProviders>
  );
}
